[package]
name = "nce-helper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.18", features = ["derive"] }
users = "0.11.0"

[[bin]]
name = "nce-helper"
path = "src/main.rs"